apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    {{ if .Values.service.targetPort }}
    targetPort: {{ .Values.service.targetPort}}
    {{ else }}
    targetPort: {{.Values.service.port }}
    {{ end }}
  type: {{ .Values.service.type }}
